Import('qt_env', 'vision')

base_libs = [vision] + qt_env["LIBS"]

widgets_src = ["views/cam.cc"]
widgets = qt_env.Library("qt_widgets", widgets_src, LIBS=base_libs)
qt_libs = [widgets] + base_libs

qt_src = ["main.cc", "window.cc"]
# qt_env.Program("ui", qt_src)
qt_env.Program("ui", qt_src, LIBS=qt_libs)
